name: viral_escape
channels:
  - bioconda
  - conda-forge
dependencies:
  - bowtie2
  - fastp
  - lofreq
  - numpy
  - pandas
  - pysam
  - python
  - samtools
  - scipy
  - snakemake
  - biopython
  - openpyxl
