configfile: "configs/JRCSF_DEMO_config.yaml"
configfile: "configs/REJOc_DEMO_config.yaml"

rule all:
    input:
        #expand("data/5-calls/{sample}.vcf", sample=config["samples"]),
        expand("data/4-sorted_reads/{sample}.bam.bai", sample=config["samples"]),
        #expand("data/6-coverage/{sample}.csv", sample=config["samples"]),
        #config["merged_output"]["var_freq"],
        config["merged_output"]["coverage"],
        config["analysis"]["average_mutation"],
        config["analysis"]["haplotype_all"],
        config["analysis"]["haplotype_nonsyn"]
        


#filter sequences
rule filter_sequences:
    input:
        R1 = "data/1-fastq_files/{sample}_R1.fastq.gz",
        R2 = "data/1-fastq_files/{sample}_R2.fastq.gz"
    params:
        tm="0",
        qs="25", # the quality value that a base is qualified. Default 15 means phred quality >=Q15 is qualified.
        ps="20" #  how many percents of bases are allowed to be unqualified (0~100). Default 40 means 40%
    log:
        "logs/fastp/{sample}.html"
    output:
        R1 = "data/2-fastq_filtered/{sample}_R1.fastq.gz",
        R2 = "data/2-fastq_filtered/{sample}_R2.fastq.gz"
    shell:
        "fastp --in1 {input.R1} --in2 {input.R2} --out1 {output.R1} --out2 {output.R2} "
        " --trim_tail1 {params.tm} --trim_tail2 {params.tm} --qualified_quality_phred {params.qs} "
        " --unqualified_percent_limit {params.ps} --html {log} --json {log}"


def get_reference(wildcards):
    reference = config["samples"][wildcards.sample].split("-")[-1].split('_')[0]
    return "data/0-reference_index/" + reference + "-reference.fa",

def get_bed(wildcards):
    reference = config["samples"][wildcards.sample].split("-")[-1].split('_')[0]
    return "data/0-bed_file/" + reference + ".bed",
    
def get_primer_bed(wildcards):
    reference = config["samples"][wildcards.sample].split("-")[-1].split('_')[0]
    return "data/0-bed_file/" + reference + "_primer.bed",
    
def get_gff(wildcards):
    reference = config["samples"][wildcards.sample].split("-")[-1].split('_')[0]
    return "data/gff/" + reference + ".gff",

def get_refname(wildcards):
    reference = config["samples"][wildcards.sample].split("-")[-1].split('_')[0]
    return "" + reference + "",
    
def get_cotig(wildcards):
    reference = config["samples"][wildcards.sample].split("-")[-1].split('_')[0]
    return reference,

def get_haplotype_bed(wildcards):
    reference = config["samples"][wildcards.sample].split("-")[-1].split('_')[0]
    return "data/0-bed_file/" + reference + "_haplotypes.bed",

#bowtie2 mapping of filtered reads
rule bowtie2_map:
    input:
        #ref = "data/0-reference_index/Rp0-reference.fa" + reference,
        ref = get_reference,
        R1 = "data/2-fastq_filtered/{sample}_R1.fastq.gz",
        R2 = "data/2-fastq_filtered/{sample}_R2.fastq.gz"
    output:
        "data/3-mapped_reads/{sample}.bam"
    log:
        "logs/bowtie2/{sample}.log"
    threads: 8
    shell:
        "(bowtie2 -p {threads} -x {input.ref} -1 {input.R1} -2 {input.R2} "
        "-S {output}) 2> {log}"

rule samtools_sort:
    input:
        "data/3-mapped_reads/{sample}.bam"
    output:
        "data/4-sorted_reads/{sample}.bam"
    shell:
        "samtools sort {input} -o {output}"

rule samtools_index:
    input:
        "data/4-sorted_reads/{sample}.bam"
    output:
        "data/4-sorted_reads/{sample}.bam.bai"
    shell:
        "samtools index {input}"

rule call:
    input:
        fa=get_reference,
        bam="data/4-sorted_reads/{sample}.bam",
        bed=get_bed
    params:
        r=40,
        b=110,
        cds="Env",
    output:
        "data/5-calls/{sample}.vcf",
        "data/6-coverage/{sample}.csv"
    script:
        "scripts/snakemake/codon_caller.py"

rule merge_freq:
    input:
        expand("data/5-calls/{sample}.vcf", sample=config["samples"])
    output:
        config["merged_output"]["var_freq"]
    script:
        "scripts/snakemake/merge_aa_freq.py"

rule merge_coverage:
    input:
        expand("data/6-coverage/{sample}.csv", sample=config["samples"])
    output:
        config["merged_output"]["coverage"]
    script:
        "scripts/snakemake/merge_coverage.py"

rule analysis:
    input:
        var_freq=config["merged_output"]["var_freq"],
        coverage=config["merged_output"]["coverage"],
        sample_list=config["metadata"]["sample_list"],
        exp_df=config["metadata"]["experiment_data"],
        HXB2_alignment=config["metadata"]["HXB2_alignment"]
    params:
        virus=config["metadata"]["virus"],
        antibody=config["metadata"]["antibody"],
        min_coverage=25,
        min_value=0.1
    output:
        average_mutation=config["analysis"]["average_mutation"],
        haplotype_all=config["analysis"]["haplotype_all"],
        haplotype_nonsyn=config["analysis"]["haplotype_nonsyn"]
    script:
        "scripts/snakemake/analysis.py"

